-- DELETE FROM BOOK;
-- DELETE FROM BOOK_STOCK;
-- DELETE FROM ACCOUNT;

INSERT INTO BOOK( ISBN, BOOK_NAME, PRICE ) VALUES( '0001', 'The First Book', 30);
INSERT INTO BOOK( ISBN, BOOK_NAME, PRICE ) VALUES( '0002', 'The Second Book', 50);
INSERT INTO BOOK_STOCK(ISBN, STOCK) VALUES('0001', 10) ;
INSERT INTO BOOK_STOCK(ISBN, STOCK) VALUES('0002', 10) ;
INSERT INTO ACCOUNT(USERNAME, BALANCE) VALUES('user1',40);
