CREATE TABLE USER_REGISTRATION
(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  FIRST_NAME VARCHAR(255) NOT NULL,
  LAST_NAME VARCHAR(255) NOT NULL,
  COMPANY VARCHAR(255) NOT NULL,
  ADDRESS VARCHAR(255) NOT NULL,
  CITY VARCHAR(255) NOT NULL,
  STATE VARCHAR(255) NOT NULL,
  ZIP VARCHAR(255) NOT NULL,
  COUNTY VARCHAR(255) NOT NULL,
  URL VARCHAR(255) NOT NULL,
  PHONE_NUMBER VARCHAR(255) NOT NULL,
  FAX VARCHAR(255) NOT NULL
);
