INSERT INTO USERS VALUES ('username', 'password', 0);
INSERT INTO USERS (USERNAME, PASSWORD, ENABLED) VALUES ('mousesd@gmail.com', '$2a$04$bnabw1IjWdVepAqxcNnODO3bglQuIbOE.Tdp5wGShttIqPcDt6cSq', 1);
INSERT INTO USERS (USERNAME, PASSWORD, ENABLED) VALUES ('mousesd@outlook.com', '$2a$04$m4em4ZyZzQUvHkXUx4VMCOvJpl0ntxqNVzN.DNQwkV3MnJwau0dRO', 1);
INSERT INTO USERS (USERNAME, PASSWORD, ENABLED) VALUES ('mousesd@icloud.com', '$2a$04$JRH5j9Zxmw8o6mNNHqb2t.vgVPdm3agPHObn7WHJly/tQIEVMmKEC', 0);

INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES('mousesd@gmail.com', 'USER');
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES('mousesd@outlook.com', 'USER');
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES('mousesd@icloud.com', 'USER');
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES('mousesd@outlook.com', 'ADMIN');
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES('mousesd@icloud.com', 'ADMIN');

/*
INSERT INTO MEMBER (ID, USERNAME, PASSWORD) VALUES (1, 'mousesd@gmail.com', '{noop}gmail');
INSERT INTO MEMBER (ID, USERNAME, PASSWORD) VALUES (2, 'mousesd@outlook.com', '{noop}outlook');
INSERT INTO MEMBER (ID, USERNAME, PASSWORD) VALUES (3, 'mousesd@icloud.com', '{noop}icloud');

INSERT INTO MEMBER_ROLE (MEMBER_ID, ROLE) VALUES(1, 'USER');
INSERT INTO MEMBER_ROLE (MEMBER_ID, ROLE) VALUES(2, 'USER');
INSERT INTO MEMBER_ROLE (MEMBER_ID, ROLE) VALUES(2, 'ADMIN');
INSERT INTO MEMBER_ROLE (MEMBER_ID, ROLE) VALUES(3, 'ADMIN');
*/
