INSERT INTO USERS VALUES ('username', 'password', 0);
INSERT INTO USERS (USERNAME, PASSWORD, ENABLED) VALUES ('mousesd@gmail.com', '{noop}gmail', 1);
INSERT INTO USERS (USERNAME, PASSWORD, ENABLED) VALUES ('mousesd@outlook.com', '{noop}outlook', 1);
INSERT INTO USERS (USERNAME, PASSWORD, ENABLED) VALUES ('mousesd@icloud.com', '{noop}icloud', 0);

INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES('mousesd@gmail.com', 'USER');
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES('mousesd@outlook.com', 'USER');
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES('mousesd@icloud.com', 'USER');
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES('mousesd@outlook.com', 'ADMIN');
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES('mousesd@icloud.com', 'ADMIN');
